-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 01, 2022 at 02:08 AM
-- Server version: 10.4.13-MariaDB
-- PHP Version: 7.4.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `darts`
--

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `games`
--

CREATE TABLE `games` (
  `id` char(36) NOT NULL DEFAULT '(uuid())',
  `player1` int(11) NOT NULL,
  `player2` int(11) DEFAULT NULL,
  `legs` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`legs`)),
  `curr_leg` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `setting` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `open_for` int(11) NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `games`
--

INSERT INTO `games` (`id`, `player1`, `player2`, `legs`, `curr_leg`, `setting`, `open_for`, `date`) VALUES
('03948ff0-0c76-43ca-b537-2a9652defa56', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[120,381,10,491],[140,241,120,371]]}\"}', '[[null,501,null,501],[179,322,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 07:52:29'),
('041bdda7-5b6f-433d-8369-039309489ab3', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":1,\"winners\":[[1,1]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[150,351,25,476],[null,null,null,null]]}\"}', '[[null,501,null,501],[150,351,120,381],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-21 12:32:56'),
('1393571a-7cd8-4264-a835-434657f4b447', 1, NULL, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":0,\"winners\":[],\"details\":[]}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-21 12:25:42'),
('225215c9-5732-43a0-90b6-a70ca6ff8cb1', 1, 2, '{\"current_leg\":3,\"sum_wins_1\":0,\"sum_wins_2\":2,\"winners\":[[2,2],[3,1]],\"details\":\"[[[null,501,null,501],[120,381,125,376],[160,221,160,216],[10,211,150,66]],[[null,501,null,501],[140,361,150,351],[150,211,10,341],[120,91,170,171]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"3\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 11:59:04'),
('25902327-b47a-4722-a25d-593b179106f2', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,1]],\"details\":\"[[[null,100,null,100],[24,76,20,80],[46,30,20,60],[30,0,null,null]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"100\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-30 03:20:20'),
('3b005c04-14c6-470a-811d-57a3bb6489b1', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[150,351,21,480],[150,201,120,360],[140,61,140,220]]}\"}', '[[null,501,null,501],[150,351,100,401],[120,231,10,391],[140,91,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"3\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 10:34:04'),
('41462fbe-da36-4e02-9e43-e17a20281644', 1, NULL, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":0,\"winners\":[],\"details\":[]}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-21 12:27:40'),
('447dc3b2-abe0-4fb4-a35b-bdd5e593b417', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[2,1]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[101,400,51,450],[20,380,150,300],[178,202,50,250],[179,23,50,200],[null,null,null,null]]}\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Ahmed\",\"player2\":\"Mohamed\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-29 06:52:46'),
('50587624-1e05-46ea-b9fc-e15674f8f126', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[2,1]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[179,322,50,451],[179,143,152,299],[null,null,null,null]]}\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":true,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-29 06:57:26'),
('57bfe92f-ca3e-4314-ae32-28c6c4dd8d68', 1, 2, '{\"current_leg\":3,\"sum_wins_1\":2,\"sum_wins_2\":0,\"winners\":[[2,2],[3,2]],\"details\":\"[[[null,501,null,501],[120,381,10,491],[120,261,10,481]],[[null,501,null,501],[120,381,100,401],[120,261,100,301]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-22 11:21:32'),
('6799e503-93c7-44bb-8409-38ed6e80ff27', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":0,\"sum_wins_2\":1,\"winners\":[[2,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[100,401,100,401],[10,391,120,281]]}\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 11:11:45'),
('6d0dde4a-22ee-4d88-a443-9337a862c8e4', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":2,\"sum_wins_2\":0,\"winners\":[[1,1],[1,1]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[179,322,20,481],[179,143,25,456],[null,null,null,null]]}\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"50\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-21 12:36:42'),
('704f790c-2600-440c-8fe7-ad9a5cff02b3', 1, 2, '{\"current_leg\":3,\"sum_wins_1\":2,\"sum_wins_2\":0,\"winners\":[[2,1],[3,1]],\"details\":\"{\\\"1\\\":[[null,200,null,200],[150,50,120,80],[null,null,null,null]],\\\"2\\\":[[null,501,null,501],[179,322,179,322],[179,143,150,172],[null,null,null,null]]}\"}', '[[null,501,null,501],[150,351,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"200\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 10:28:51'),
('7adf6425-24d8-4389-b350-6c71935fab64', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,1]],\"details\":\"[[[null,100,null,100],[50,50,10,90],[null,null,null,null]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"100\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-30 02:49:12'),
('8889a35b-9f67-4310-ac2b-3f8fdcc22585', 1, 2, '{\"current_leg\":5,\"sum_wins_1\":2,\"sum_wins_2\":2,\"winners\":[[1,1],[2,2],[3,2],[4,1]],\"details\":\"[[[null,501,null,501],[150,351,12,489]],[[null,501,null,501],[23,478,25,476]],[[null,501,null,501],[20,481,120,381]],[[null,501,null,501],[120,381,10,491]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"1\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-30 02:41:12'),
('93c8a630-2203-4754-a292-4f0b84d8daf5', 1, 2, '{\"current_leg\":3,\"sum_wins_1\":2,\"sum_wins_2\":0,\"winners\":[[2,1],[3,1]],\"details\":\"{\\\"1\\\":[[null,50,null,50],[null,null,null,null]],\\\"2\\\":[[null,501,null,501],[179,322,25,476],[179,143,25,451],[null,null,null,null]]}\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"50\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-21 12:38:59'),
('945d07d3-5fc9-4461-b089-f90b29036ee7', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,1]],\"details\":\"[[[null,101,null,101],[51,50,20,81],[20,30,21,60],[30,0,null,null]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"101\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-30 03:05:59'),
('94e0c21d-a0c8-4c30-a802-499ba2807510', 1, 2, '{\"current_leg\":3,\"sum_wins_1\":1,\"sum_wins_2\":1,\"winners\":[[1,1],[2,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[150,351,100,401],[120,231,20,381]],\\\"2\\\":[[null,501,null,501],[20,481,150,351],[32,449,120,231]]}\"}', '[[null,501,null,501],[150,351,25,476],[null,null,150,326]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-30 02:31:21'),
('bb367f09-f203-4da5-9a59-701ed70c1f54', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[1,1]],\"details\":\"[[[null,50,null,50],[50,0,null,null]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":\"50\",\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-21 12:39:00'),
('bbdfba40-c412-4026-a16c-be7de40b2290', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":0,\"winners\":[],\"details\":[]}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"unsaved\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-30 18:43:22'),
('c1cca4a3-257e-49ff-a820-a255c7d9671e', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":0,\"winners\":[],\"details\":[]}', '[[null,501,null,501],[120,381,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":true,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-29 07:02:45'),
('c671330e-8162-4644-a994-4f666eac55af', 1, 2, '{\"current_leg\":5,\"sum_wins_1\":2,\"sum_wins_2\":2,\"winners\":[[2,2],[3,2],[4,2],[5,1]],\"details\":\"[[[null,501,null,501],[120,381,12,489]],[[null,501,null,501],[120,381,100,401]],[[null,501,null,501],[120,381,150,351]],[[null,501,null,501],[120,381,150,351]]]\"}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"1\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 11:25:37'),
('cf77ad5d-459e-4449-b921-ce6bab039f23', 1, 2, '{\"current_leg\":4,\"sum_wins_1\":3,\"sum_wins_2\":0,\"winners\":[[2,2],[3,2],[4,2]],\"details\":\"[[[null,501,null,501],[150,351,120,381],[140,211,100,281],[120,91,20,261]],[[null,501,null,501],[140,361,10,491],[100,261,20,471],[120,141,12,459]],[[null,501,null,501],[120,381,12,489],[140,241,121,368],[41,200,10,358]]]\"}', '[[null,501,null,501],[12,489,25,476],[14,475,32,444],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"3\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-29 23:58:46'),
('e0e42414-422a-4fbc-a68c-a12e512ebde7', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":0,\"sum_wins_2\":0,\"winners\":[],\"details\":[]}', '[[null,501,null,501],[null,null,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":null,\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"unsaved\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 0, '2022-06-30 03:45:32'),
('e56581e5-42aa-4310-9abb-b903565ef098', 1, 2, '{\"current_leg\":2,\"sum_wins_1\":1,\"sum_wins_2\":0,\"winners\":[[2,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[120,381,10,491],[120,261,120,371]]}\"}', '[[null,501,null,501],[100,401,12,489],[120,281,null,null]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 2, '2022-06-22 11:15:19'),
('f7f7d134-0be2-4edc-b377-f06e91efd37f', 1, 2, '{\"current_leg\":1,\"sum_wins_1\":1,\"sum_wins_2\":1,\"winners\":[[1,2],[1,2]],\"details\":\"{\\\"1\\\":[[null,501,null,501],[10,491,120,381],[12,479,120,261]]}\"}', '[[null,501,null,501],[160,341,150,351],[null,null,100,251]]', '{\"player1\":\"Player 1\",\"player2\":\"Player 2\",\"start_score\":501,\"limit_rounds\":\"2\",\"remaining_score\":0,\"com_score\":0,\"handicap_1\":0,\"handicap_2\":0,\"double_in\":0,\"double_out\":0,\"game_title\":\"Game Generated By : Ahmed\"}', 1, '2022-06-22 10:44:03');

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '0000_00_00_000000_create_websockets_statistics_entries_table', 2);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Ahmed', 'ahmed@ahmed.com', NULL, '$2y$10$/AZRCBC.5I0feKCRm7HDAuyiu/MonG.FUhYU1IuKkudvYkpFvMXGO', NULL, '2022-06-05 23:15:33', '2022-06-05 23:15:33'),
(2, 'Ahmed 2', 'a2@gmail.com', NULL, '$2y$10$T2pzScEt0Z7f7MYmUHAkrueLsQe/ZceuADKuwbSOiTmB7OQ8MnmPC', NULL, '2022-06-06 00:39:31', '2022-06-06 00:39:31'),
(3, 'Bido', 'bido@b.com', NULL, '$2y$10$xypuDVLav2PvtE2VtgLnMOiqVN7JIMT.Wj5bjkqi7ePnyIhy0TuOe', NULL, '2022-06-06 18:49:33', '2022-06-06 18:49:33');

-- --------------------------------------------------------

--
-- Table structure for table `websockets_statistics_entries`
--

CREATE TABLE `websockets_statistics_entries` (
  `id` int(10) UNSIGNED NOT NULL,
  `app_id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `peak_connection_count` int(11) NOT NULL,
  `websocket_message_count` int(11) NOT NULL,
  `api_message_count` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `games`
--
ALTER TABLE `games`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- Indexes for table `websockets_statistics_entries`
--
ALTER TABLE `websockets_statistics_entries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `websockets_statistics_entries`
--
ALTER TABLE `websockets_statistics_entries`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
